class ExerciseError(Exception):
    ...

class ExerciseNotFoundError(ExerciseError):
    ...

class InvalidExerciseError(ExerciseError):
    ...

class ExerciseAlreadyExistsError(ExerciseError):
    ...
